# Generated by Django 4.2.30 on 2026-07-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('it_support', 'IT Support'), ('access', 'Access'), ('admin_issue', 'Admin Issue'), ('hr', 'HR')], db_index=True, default='it_support', max_length=20),
        ),
    ]
